name: Actionlint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
